### ISSUE TITLE
Bump winit for 0.1.0 to 0.26+

### ISSUE THREAD

**Issue by GotoFinal** [temportalflux/input-actions#1]
Any chance to bump winit version for this lib? Trying to use it in my project but i need at least 0.26 and the example no longer compiles with it. Tried to also use current master but examples in readme are outdated for it.

**Comment by temportalflux** [comment]
I surprised anyone is even using this haha. I havent even fully finished proving out the concept yet, but yeah lemme see if I can upgrade winit for ya

**Comment by temportalflux** [comment]
Ok, I branched off of the `0.1.0` release to upgrade `winit` to `0.26` and released as [`0.1.1`](https://crates.io/crates/input-actions). You should be good to go.
As a general warning, this crate is still undergoing heavy rehauling and changes (which is why the code sample on `main` doesnt actually match how the crate is used on that branch). I've updated the README to reflect this.

**Comment by GotoFinal** [comment]
@temportalflux Ah i see now that 0.1.0 is pretty incomplete, as some important values are not even exposed, like `value` from state, making axis not usable. Will keep observing project as seems there is no simple input handling library for rust yet.

**Comment by temportalflux** [comment]
@GotoFinal appreciate it! I'm looking forward to digging into this concept once I dig through some other problems on the networking and rendering side for https://github.com/temportalflux/crystal-sphinx
